{{- if .Values.exporter.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drl.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "drl.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ tpl (toYaml .Values.exporter.auth.dockerHubPassword) . | sha256sum }}
type: Opaque
data:
  dockerhub-username: {{ .Values.exporter.auth.dockerHubUsername | b64enc | quote  }}
  dockerhub-password: {{ .Values.exporter.auth.dockerHubPassword | b64enc | quote  }}
{{- end }}