
apiVersion: v1
kind: Service
metadata:
  name: {{ include "drl.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "drl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ default 2121 .Values.exporter.listenPort }}
      protocol: TCP
      targetPort: {{ .Values.exporter.listenPort }}
  selector:
  {{- include "drl.selectorLabels" . | nindent 4 }}
