apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipup.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ipup.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ tpl (toYaml .Values.ipup.config.password ) . | sha256sum }}
type: Opaque
data:
  dynu-username: {{ .Values.ipup.config.username | b64enc | quote  }}
  dynu-password: {{ .Values.ipup.config.password | b64enc | quote  }}
