{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ipup.labels" . | nindent 4 }}
{{- end }}
