--- 
{{- if .Values.runner.config.enabled  }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ar.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ar.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ tpl (toYaml .Values.runner.config.data) . | sha256sum }}
data:
  config.yaml: {{ .Values.runner.config.data | b64enc }}
{{- end }}
