{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (not .Values.runner.useStatefulSet) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ar.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ar.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessModes }}
  {{- if .Values.persistence.selector }}
  selector: {{ toYaml .Values.persistence.selector | nindent 8 }}
  {{- end }}
{{- end }}
