{{- if eq .Values.runner.runnerToken.existingSecret "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ar.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ar.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ tpl (toYaml .Values.runner.runnerToken.value) . | sha256sum }}
type: Opaque
data:
  token: {{ .Values.runner.runnerToken.value | b64enc | quote }}
{{- end }}