apiVersion: v2
name: pingme
version: 0.1.2
description: Multi-platform notification service
type: application
keywords:
  - pingme
  - webhook
  - notification
home: https://charts.tektonops.com
maintainers:
  - name: Abdul Khaliq
    email: a.khaliq@outlook.my
    url: https://github.com/tektonops/charts
appVersion: 0.1.1
