
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pingme.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "pingme.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ default 8080 .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
  {{- include "pingme.selectorLabels" . | nindent 4 }}
